services:
  backend:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: "../apps/backend/"
      target: dev
    ports:
      - "${API_PORT:-8000}:8000"
    volumes:
      - "../apps/backend/app/:/app/app/"
    restart: unless-stopped
    env_file:
      - ../apps/backend/.env

  db:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: "${DB_USER:-appuser}"
      POSTGRES_DB: "${DB_NAME:-simulation}"
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-appuser} -d ${DB_NAME:-simulation}"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    env_file:
      - ../apps/backend/.env

  pgadmin:
    depends_on:
      - db
    image: dpage/pgadmin4:9.10
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    logging:
      driver: none
    configs:
      - source: pgadmin-pgpass
        target: /config/pgpass
        uid: "5050"
        gid: "5050"
        mode: 0400
      - source: pgadmin-servers
        target: /pgadmin4/servers.json
        mode: 0444

volumes:
  db_data:

configs:
  pgadmin-servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Local Postgres",
            "Group": "Servers",
            "Host": "db",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "appuser",
            "PassFile": "/config/pgpass"
          }
        }
      }

  pgadmin-pgpass:
    content: |
      db:5432:*:appuser:fastapi_db_password